
emb_path_list=(\
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split1_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split2_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split3_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split4_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split5_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split6_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split7_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split8_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split9_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split10_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split11_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split12_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split13_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split14_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split15_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split16_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split17_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split18_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split19_list.pt" \
"/data/wikilinks/reduced_aggregated_preprocessed_common_noun_512tokens_non_ne_vocabwikilinks_more_10_split20_list.pt" \
)


python3 convert_list_into_tensor.py  --emb_path ${emb_path_list[@]} 
wait

